DROP TABLE IF EXISTS CAFEUSER, ARTICLE, REPLY;

CREATE TABLE CAFEUSER
(
    USER_ID  VARCHAR(100) PRIMARY KEY,
    PASSWORD VARCHAR(100) NOT NULL,
    NAME     VARCHAR(100) NOT NULL,
    EMAIL    VARCHAR(100) NOT NULL
);

CREATE TABLE ARTICLE
(
    ARTICLE_ID INT PRIMARY KEY ,
    USER_ID    VARCHAR(100) NOT NULL,
    TITLE      VARCHAR(100) NOT NULL,
    CONTENTS   VARCHAR(255) NOT NULL,
    TIME       VARCHAR(100) NOT NULL,
    DELETED    BOOLEAN NOT NULL,
    FOREIGN KEY (USER_ID) REFERENCES CAFEUSER (USER_ID)
);

CREATE TABLE REPLY
(
    REPLY_ID   INT PRIMARY KEY,
    USER_ID    VARCHAR(100) NOT NULL,
    ARTICLE_ID INT NOT NULL,
    CONTENTS   VARCHAR(255) NOT NULL,
    TIME       VARCHAR(100) NOT NULL,
    DELETED    BOOLEAN NOT NULL,
    FOREIGN KEY (ARTICLE_ID) REFERENCES ARTICLE (ARTICLE_ID)
);
