DROP TABLE IF EXISTS CAFEUSER, ARTICLE, REPLY;

CREATE TABLE CAFEUSER
(
    USER_ID  VARCHAR PRIMARY KEY,
    PASSWORD VARCHAR NOT NULL,
    NAME     VARCHAR NOT NULL,
    EMAIL    VARCHAR NOT NULL
);

CREATE TABLE ARTICLE
(
    ARTICLE_ID INT PRIMARY KEY,
    USER_ID    VARCHAR NOT NULL,
    TITLE      VARCHAR NOT NULL,
    CONTENTS   VARCHAR NOT NULL,
    TIME       VARCHAR NOT NULL,
    DELETED    boolean NOT NULL,
    FOREIGN KEY (USER_ID) REFERENCES CAFEUSER (USER_ID)
);

CREATE TABLE REPLY
(
    REPLY_ID INT PRIMARY KEY,
    USER_ID    VARCHAR NOT NULL,
    ARTICLE_ID INT NOT NULL,
    CONTENTS   VARCHAR NOT NULL,
    TIME       VARCHAR NOT NULL,
    DELETED    boolean NOT NULL,
    FOREIGN KEY (ARTICLE_ID) REFERENCES ARTICLE (ARTICLE_ID) ON DELETE CASCADE
);
