INSERT INTO CAFE_USER(USERID, PASSWORD, NAME, EMAIL)
VALUES ('test', '1234', 'tester', 'test01@naver.com');

INSERT INTO CAFE_USER(USERID, PASSWORD, NAME, EMAIL)
VALUES ('jhc1426', '1111', 'ManJu', '11111@gmail.com');

INSERT INTO CAFE_ARTICLE(WRITER, TITLE, CONTENTS)
VALUES ('ManJu', '테스트01', '테스트용 글 입니돵');
